name: CI/CD Pipeline for Eco-Tourism Web App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed] # Runs only when a PR is merged (closed) into `main`
    
jobs:
  build-and-test:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Recommended LTS version

      - name: Install dependencies
        working-directory: ./Eco-Tourism # Navigate to eco-tourism folder
        run: npm ci # Clean install for CI environments

      - name: Run tests
        working-directory: ./Eco-Tourism # Navigate to eco-tourism folder
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # This ensures the repository is available
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        id: deploy
        run: |
          npm install -g vercel
          
          # Deploy to Vercel without creating additional auto-generated domains
          DEPLOY_URL=$(vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }} --name eco-tourism --cwd ./Eco-Tourism)
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV


      - name: Assign Custom Domain
        run: |
        
          # Fetch the list of existing aliases
          EXISTING_ALIASES=$(vercel alias ls --token=*** | awk 'NR>2 {print $2}' | grep -v '^eco-tourism-f.vercel.app$')

          # Loop through each alias and remove it
          while read -r ALIAS; do
            if [[ -n "$ALIAS" ]]; then
            echo "Removing alias: $ALIAS"
            vercel alias rm "$ALIAS" --token=***
            fi
          done <<< "$EXISTING_ALIASES"

          # Assign only the correct alias
          vercel alias set eco-tourism-f.vercel.app --token=***
